# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180713_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
